Fixed outdated links
OffchainLabs/arbitrum-docs pull request #1588
Opened 2024-08-26 07:18 UTC by fasteater

2024-08-26 13:00 UTC, hkalodner commented
@cla-bot check

2024-08-30 14:03 UTC, anegg0 commented on arbitrum-docs/stylus/stylus-quickstart.md
> +To read more about what counts as valid vs. invalid user WASM programs, see [VALID_WASM](https://github.com/OffchainLabs/cargo-stylus/blob/main/check/VALID_WASM.md). If your program succeeds, you'll
This link doesn't seem to be valid. Can you specify what you were pointing to, @fasteater?

2024-08-30 14:05 UTC, anegg0 requested changes
LGTM for the dependi extension.
The VALID_WASM link you added returns a 404, though.

2024-09-04 11:58 UTC, anegg0 commented on arbitrum-docs/stylus/stylus-quickstart.md
> +To read more about what counts as valid vs. invalid user WASM programs, see [VALID_WASM](https://github.com/OffchainLabs/cargo-stylus/blob/main/check/VALID_WASM.md). If your program succeeds, you'll
This link has been updated since.

2024-09-04 12:01 UTC, anegg0 approved these changes
LGTM

2024-09-04 12:01 UTC, merged

2024-09-04 12:02 UTC, anegg0 commented
Thank you for the dependi  extension link update, @fasteater :)