change language in verify docs to specify 0.5.0 or higher
OffchainLabs/arbitrum-docs pull request #1636
Opened 2024-09-03 18:50 UTC by leeederek

2024-09-03 18:50 UTC, mahsamoosavi approved these changes

2024-09-03 20:22 UTC, anegg0 requested changes
One nit away from merging.

2024-09-03 20:22 UTC, anegg0 commented on arbitrum-docs/stylus/how-tos/verifying-contracts.mdx
> +This page will walk you through how to verify your Stylus contracts locally. However, Stylus contract verification is available on [Arbiscan](https://arbiscan.io/) as well. Please note, however, that
```suggestion
This page will walk you through how to verify your Stylus contracts locally. Stylus contract verification is also available on [Arbiscan](https://arbiscan.io/). Please note, however, that Stylus contract verification on Arbiscan is only supported for Stylus contracts deployed using `cargo-stylus` 0.5.0 or higher. 
```

2024-09-04 09:54 UTC, anegg0 approved these changes

2024-09-04 10:58 UTC, merged