[WIP / Draft] Stylus V2 New IA
OffchainLabs/arbitrum-docs pull request #1804
Opened 2024-11-06 22:46 UTC by srinjoyc

2024-11-15 16:21 UTC, srinjoyc commented
I ran `yarn format` in the website directory  and tried manually running prettier on the file - it seems to product no warnings / errors locally. Not sure what the issue is..

2024-11-15 20:19 UTC, joshuacolvin0 approved these changes

2024-11-20 15:43 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +There are four main steps for bringing a Stylus program to life: <b>coding, activation, execution, and proving.</b>
```suggestion
There are four main steps for bringing a Stylus program to life: **coding, activation, execution, and proving**.
```

2024-11-20 15:44 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Developers can now write smart contracts in any programming language that compiles to WASM. Note that some high-level languages generate far more performant WASMs than others.
```suggestion
Developers can now write smart contracts in any programming language that compiles to WASM.

:::note
Some high-level languages generate far more performant WASMs than others.
:::
```

2024-11-20 15:45 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Initially, there will be support for Rust, C, and C++. However, the levels of support will differ at first. Rust has rich language support from day one, with an open-source SDK that makes writing sma
```suggestion
Initially, there will be support for Rust, C, and C++. However, the levels of support will vary. Rust has rich language support from day one, with an open-source SDK that makes writing smart contracts in Rust as easy as possible. C and C++ are supported off the bat, enabling the deployment of existing contracts in those languages on-chain with minimal modifications.
```

2024-11-20 15:46 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +The Stylus SDK for Rust contains the smart contract development framework and language features most developers will need to use in Stylus. The SDK also makes it possible to perform all of the EVM-sp
```suggestion
The Stylus SDK for Rust contains the smart contract development framework and language features most developers will need to use in Stylus. The SDK also makes it possible to perform all EVM-specific functionalities that smart contract developers use. Check out the [Rust SDK Guide](https://docs.arbitrum.io/stylus/rust-sdk-guide) and the [Crate Docs](https://docs.rs/stylus-sdk/latest/stylus_sdk/index.html).
```

2024-11-20 15:49 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Stylus programs are compiled to WASM and then lowered to assembly. Starting from a high-level language (such as Rust, C, or C++), the first compilation stage happens either using the CLI provided in
```suggestion
Stylus programs are compiled to WASM, and then lowered to assembly. Starting from a high-level language (such as Rust, C, or C++), the first compilation stage happens using the CLI provided in the Stylus SDK for Rust or any other compiler, such as Clang for C and C++. Once compiled, the WASM is posted onchain. Then, in an activation process, WASM gets lowered to a node's native machine code (such as ARM or x86).
```

2024-11-20 15:57 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Gas metering is essential for certifying that computational resources are paid for. In Stylus, the unit for measuring cost is called “ink,” similar to Ethereum's gas but thousands of times smaller. T
```suggestion
Gas metering is essential for certifying that computational resources are paid for. In Stylus, the unit for measuring cost is called **ink**, which is similar to Ethereum's gas but thousands of times smaller. There are two reasons why a new measurement is used: First, WASM execution is so much faster than the EVM that executing thousands of WASM opcodes could be done in the same amount of time it takes the EVM to execute one. Second, the conversion rate of ink to gas can change based on future hardware or VM improvements. For a conceptual introduction to Stylus gas and ink, see [gas and ink (Stylus)](https://docs.arbitrum.io/stylus/concepts/stylus-gas).
```

2024-11-20 15:57 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Gas metering is essential for certifying that computational resources are paid for. In Stylus, the unit for measuring cost is called “ink,” similar to Ethereum's gas but thousands of times smaller. T
I would suggest defining ink and linking to glossary

2024-11-20 15:59 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Stylus programs are executed in a fork of [Wasmer](https://wasmer.io/), the leading WebAssembly runtime, with minimal changes to optimize their codebase for blockchain-specific use cases. Wasmer exec
```suggestion
Stylus programs execute in a fork of [Wasmer](https://wasmer.io/), the leading WebAssembly runtime, with minimal changes to optimize their codebase for blockchain-specific use cases. Wasmer executes native code much faster than <a data-quicklook-from="geth">Geth</a> executes EVM bytecode, contributing to the significant gas savings that Stylus provides.
```

2024-11-20 16:03 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +EVM contracts continue to execute the same way they did before Stylus. When a contract is called, the difference between an EVM contract and a WASM program can be seen via an [EOF](https://notes.ethe
```suggestion
EVM contracts continue to execute the same way they were before Stylus. When calling a contract, the difference between an EVM contract and a WASM program is visible via an [EOF](https://notes.ethereum.org/@ipsilon/evm-object-format-overview)-inspired contract header. From there, the contract executes using its corresponding runtime. Contracts written in Solidity and WASM languages can make cross-contract calls to each other, meaning a developer never has to consider which language the contract is in. Everything is interoperable.
```

2024-11-20 16:06 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +There are estimated to be roughly 20k Solidity developers, compared to 3 million Rust developers or 12 million C developers [[1](https://slashdatahq.medium.com/state-of-the-developer-nation-23rd-edit
```suggestion
There are roughly 20k Solidity developers, compared to 3 million Rust developers or 12 million C developers [[1](https://slashdatahq.medium.com/state-of-the-developer-nation-23rd-edition-the-fall-of-web-frameworks-coding-languages-711525e3df3a)]. Developers can now use their preferred programming language, which is  interoperable on any <a data-quicklook-from="arbitrum-chain">Arbitrum chain</a> with Stylus. By onboarding the next million developers, scaling to the next billion users becomes possible.
```

2024-11-20 16:07 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Stylus doesn't just improve on cost and speed. WASM programs are also safer. Reentrancy is a common vulnerability that developers can only attempt to mitigate in Solidity. Stylus provides cheap reent
```suggestion
Stylus doesn't just improve on cost and speed. WASM programs are also safer. Reentrancy is a common vulnerability developers can only attempt to mitigate in Solidity. Stylus provides cheap reentrancy detection, and using the Rust SDK, reentrancy is disabled by default unless intentionally overridden.
```

2024-11-20 16:12 UTC, pete-vielhaber commented on arbitrum-docs/stylus/stylus-gentle-introduction.md
> +With a WASM VM, any programming language that can compile to WASM is within Stylus's scope. While many popular programming languages can be compiled into WASM, some compilers are more suitable for sm
```suggestion
With a WASM VM, any programming language compilable to WASM is within Stylus's scope. While many popular programming languages can compile into WASM, some compilers are more suitable for smart contract development than others, like Rust, C, and C++. Other languages like Go, Sway, Move, and Cairo are also  supported. Languages that include their own runtimes, like Python and Javascript, are more complex for Stylus to support, although not impossible. Compared to Solidity, WASM programs are much more efficient for memory-intensive applications. There are many reasons for this, including the decades of compiler development for Rust and C. WASM also has a faster runtime than the EVM, resulting in faster execution. Third-party [contribution](#contributing) in the form of libraries for new and existing languages is welcomed!
```

2024-11-20 16:16 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +### Coding
```suggestion
## Coding
```

2024-11-20 16:16 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +### Activation
```suggestion
## Activation
```

2024-11-20 16:16 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +### Execution
```suggestion
## Execution
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +### Why does this matter?
```suggestion
## Why does this matter?
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +#### One chain, many languages
```suggestion
### One chain, many languages
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +#### A better EVM
```suggestion
### A better EVM
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +#### Cheaper execution
```suggestion
### Cheaper execution
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +#### Opt-in reentrancy
```suggestion
### Opt-in reentrancy
```

2024-11-20 16:17 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +#### Fully interoperable
```suggestion
### Fully interoperable
```

2024-11-20 16:20 UTC, pete-vielhaber commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Stylus is a more efficient execution environment than the EVM, leading directly to gas savings for complex smart contracts. Computation and memory can be significantly cheaper. Cryptography libraries
```suggestion
Stylus is a more efficient execution environment than the EVM, leading directly to gas savings for complex smart contracts. Computation and memory can be significantly cheaper. Deploying cryptography libraries can be done permissionlessly as custom application layer precompiles. Use cases that are impractical in the EVM are now possible in Stylus.
```

2024-11-26 03:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OffchainLabs/arbitrum-docs?pullRequest=1804) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/OffchainLabs/arbitrum-docs?pullRequest=1804) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: anegg0<br/>:x: srinjoyc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OffchainLabs/arbitrum-docs?pullRequest=1804) it.</sub>

2024-12-04 14:50 UTC, joshuacolvin0 approved these changes

2024-12-04 14:50 UTC, joshuacolvin0 commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Initially, there will be support for Rust, C, and C++. However, the levels of support will vary. Rust has rich language support from day one, with an open-source SDK that makes writing smart contract
```suggestion
Currently there is support for Rust, C, and C++. However, the levels of support varies. Rust has rich language support from day one, with an open-source SDK that makes writing smart contracts in Rust as easy as possible. C and C++ is supported off the bat, enabling the deployment of existing contracts in those languages on-chain with minimal modifications.
```

2024-12-04 14:50 UTC, joshuacolvin0 commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +Stylus programs are compiled to WASM, and then lowered to assembly. Starting from a high-level language (such as Rust, C, or C++), the first compilation stage happens using the CLI provided in the St
```suggestion
Starting from a high-level language (such as Rust, C, or C++), the first compilation stage happens using the CLI provided in the Stylus SDK for Rust or any other compiler, such as Clang for C and C++. Once compiled, the WASM is posted onchain. Then, in an activation process, WASM gets lowered to a node's native machine code (such as ARM or x86).
```

2024-12-04 20:09 UTC, joshuacolvin0 approved these changes
LGTM

2024-12-09 16:23 UTC, pete-vielhaber approved these changes
- Made a single suggestion

2024-12-09 17:43 UTC, anegg0 commented on arbitrum-docs/stylus/concepts/how-it-works.md
> +The Stylus SDK for Rust contains the smart contract development framework and language features most developers will need to use in Stylus. The SDK also makes it possible to perform all EVM-specific
```suggestion
Developers can now write smart contracts in any programming language that compiles to WASM.

:::note
Some high-level languages generate far more performant WASMs than others.
:::

Currently, there is support for Rust, C, and C++. However, the levels of support vary. Rust has rich language support from day one, with an open-source SDK that makes writing smart contracts in Rust as easy as possible. C and C++ are supported off the bat, enabling the deployment of existing contracts in those languages on-chain with minimal modifications.

The Stylus SDK for Rust contains the smart contract development framework and language features most developers will need to use in Stylus. The SDK also makes it possible to perform all EVM-specific functionalities that smart contract developers use. Check out the [Rust SDK Guide](https://docs.arbitrum.io/stylus/rust-sdk-guide) and the [Crate Docs](https://docs.rs/stylus-sdk/latest/stylus_sdk/index.html).
```

2024-12-09 17:50 UTC, anegg0 requested changes
I suggested a few grammar fixes. Once those have been addressed, it all LGTM.

2024-12-09 18:42 UTC, anegg0 approved these changes

2024-12-09 19:37 UTC, merged