feat: tmp structure
OffchainLabs/arbitrum-docs pull request #1815
Opened 2024-11-13 01:05 UTC by anegg0

This is a WIP implementation of the Orbit V3 content structure.

2025-01-08 18:02 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The challenge period defines the time frame during which state updates (assertions) submitted to a child chain remain open for scrutiny and potential challenges before they are finalized. This mechan
```suggestion
The challenge period defines the time frame during which state updates (assertions) submitted to the parent chain remain open for scrutiny and potential challenges before they are finalized. This mechanism ensures that participants in the system —whether on a rollup or an AnyTrust Orbit chain— have the opportunity to verify the validity of state updates and raise challenges if necessary.
```
Why explicitly mention "rollup or Anytrust"? If that clarification doesn't add value, we can maybe remove it (the text between '—').

2025-01-08 18:04 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The length of the challenge period is measured in parent chain blocks, allowing for a predictable and flexible configuration regardless of the use case.
```suggestion
The length of the challenge period is measured in the parent chain notion of block.number, allowing for a predictable and flexible configuration regardless of the use case.
```
Or something similar. Saying "parent chain blocks" is not accurate, since L3s settling to Arbitrum chains will be measured by L1 block times.

2025-01-08 18:05 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The length of the challenge period is measured in parent chain blocks, allowing for a predictable and flexible configuration regardless of the use case.
Maybe it's a good idea to explicitly mention that scenario btw (L3s settling to Arbitrum)

2025-01-08 18:07 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +In addition to the main challenge period, an **extra challenge period** provides a buffer that allows for the resolution of any pending challenges after the main period ends. Together, these paramete
I think "transaction finality" might be confusing in this context, since the reader might think that a transaction is not finalized until the state is confirmed on the parent chain. Maybe something like "confirmation of the chain's state" or something like that?

2025-01-08 18:09 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to 45,818 blocks on the parent chain. This default is designed to provide sufficient time for validators to detect and cha
```suggestion
By default, the challenge period lasts approximately one week, corresponding to 45,818 blocks on the parent chain's notion of block.numer. This default is designed to provide sufficient time for validators to detect and challenge fraudulent assertions.
```
I'm not entirely happy with this, tbh 😅 . There's probably a better alternative, but I just want to flag that the current definition is not accurate.

2025-01-08 18:12 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The extra challenge period, on the other hand, adds a buffer of 200 parent chain blocks (approximately 40 minutes). This ensures that any last-minute challenges or ongoing dispute resolution processe
Same here, it's parent chain's notion of block.number, or a probably better term. Also, the 40 minutes apply to chains settling to Arbitrum chains or Ethereum.

2025-01-08 18:12 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +### Default challenge period and extra challenge period
I can't see the preview, but shouldn't these be h2 titles? `##`

2025-01-08 18:13 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The main challenge period is configured using the `confirmPeriodBlocks` parameter, which specifies the duration of the challenge window in terms of parent chain blocks. This parameter can be customiz
Same issue with "parent chain blocks"

2025-01-08 18:16 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +2. **Post-deployment**: The rollup admin can update this value dynamically by calling the `Rollup.setConfirmPeriodBlocks(newValue)` function.
```suggestion
2. **Post-deployment**: The chain owner can update this value dynamically by calling the `Rollup.setConfirmPeriodBlocks(newValue)` function.
```
Maybe? To be consistent with the language we use in other pages, not sure.

2025-01-08 18:17 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +   RollupAdminLogic.setExtraChallengeTimeBlocks(300);
We can maybe provide a cast command here instead? wdyt?

2025-01-08 18:17 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +   This would set the extra challenge period to 300 parent chain blocks.
Same issue with "parent chain blocks"

2025-01-08 18:18 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Challenge period blocks**: 45,818 parent chain blocks (approximately one week).
Here, and the next point, the same issue with "parent chain blocks"

2025-01-08 18:23 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Shorter periods**: Suitable for use cases demanding faster transaction finality, such as high-frequency trading or gaming platforms.
Same problem here with "transaction finality". We should change that to something like "state confirmation" or similar.

Also, I don't think this is relevant for high-frequency tranding or gaming platforms. They can still operate as fast as they wish regardless of the challenge period configuration.

2025-01-08 18:24 UTC, TucksonDev requested changes
A review for the new "Customizable challenge period" page (haven't reviewed other changes).

This is great @mahsamoosavi , thanks! It's going to help a lot. I added some comments there mostly about terms that are not entirely accurate and might be confusing.

2025-01-31 20:21 UTC, mahsamoosavi commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +2. **Post-deployment**: The rollup admin can update this value dynamically by calling the `Rollup.setConfirmPeriodBlocks(newValue)` function.
Agreed yea

2025-01-31 20:25 UTC, mahsamoosavi commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +   RollupAdminLogic.setExtraChallengeTimeBlocks(300);
it'd be more interactive yea, I'll add that

2025-01-31 21:03 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The length of the challenge period is measured based on the parent chain's notion of time, typically reflected in `block.number`. For L3s settling to Arbitrum chains, this period is determined by L1
```suggestion
The length of the challenge period is measured based on the parent chain's notion of time, typically reflected in `block.number`. For L3s settling to Arbitrum chains, this period is determined by L1 block progression rather than Arbitrum's (L2) blocks.
```

2025-01-31 21:04 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +In addition to the main challenge period, ** an extra challenge period ** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance secur
```suggestion
In addition to the main challenge period, ** an extra challenge period ** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance security and confirm the chain's state.
```

2025-01-31 21:09 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. For chains settling to Ethereum, this equates to roughly 45,818 L1 bloc
```suggestion
By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethereum. The default duration design is to provide sufficient time for validators to detect and challenge fraudulent assertions.
```

2025-01-31 21:10 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The extra challenge period, on the other hand, adds a buffer of 200 blocks based on the parent chain’s notion of block progression. For chains settling to Ethereum, this corresponds to approximately
```suggestion
The extra challenge period, on the other hand, adds a buffer of 200 blocks based on the parent chain’s notion of block progression. For chains settling to Ethereum, this corresponds to approximately 40 minutes. This time ensures that any last-minute challenges or ongoing dispute resolution processes can be completed before the rollup finalizes its state.
```

2025-01-31 21:16 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The main challenge period is configured using the `confirmPeriodBlocks` parameter, which specifies the duration of the challenge window based on the parent chain’s notion of block progression. This p
```suggestion
The main challenge period configuration uses the `confirmPeriodBlocks` parameter, which specifies the duration of the challenge window based on the parent chain’s notion of block progression. This parameter can is customizable in two ways:
```

2025-01-31 21:17 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +For example, setting `confirmPeriodBlocks` to 30,000 blocks reduces the challenge period to approximately 4.5 days. This might be suitable for applications prioritizing faster state confirmation, whi
```suggestion
For example, setting `confirmPeriodBlocks` to 30,000 blocks reduces the challenge period to approximately 4.5 days. This configuration might be suitable for applications prioritizing faster state confirmation, while increasing the value would extend the challenge period, improving security.
```

2025-01-31 21:19 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The extra challenge period is governed by the `extraChallengeTimeBlocks` parameter, which defines the additional buffer duration after the main challenge period. This ensures that any pending challen
```suggestion
The extra challenge period is governable using the `extraChallengeTimeBlocks` parameter, which defines the additional buffer duration after the main challenge period. This period ensures that pending challenges are processed before the rollup state gets finalized.
```

2025-01-31 21:19 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the extra challenge period is set to **200 blocks**, providing a short but sufficient buffer for most networks. However, developers can increase this value for applications that require a
```suggestion
By default, the extra challenge period is set to **200 blocks**, providing a short but sufficient buffer for most networks. However, developers can increase this value for applications requiring additional dispute resolution time or operate in environments with higher latency between the parent and child chain.
```

2025-01-31 21:20 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +Like the main challenge period, this parameter can be customized in two ways:
```suggestion
Like the main challenge period, this parameter can is customizable in two ways:
```

2025-01-31 21:21 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +For example, the following command can be used to update the extra challenge period to 300 blocks, based on the parent chain’s notion of block progression:
```suggestion
For example, the following command can update the extra challenge period to 300 blocks based on the parent chain’s notion of block progression:
```

2025-01-31 21:22 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Shorter periods**: Suitable for applications that benefit from faster state confirmation, such as rollups prioritizing quicker exits or user withdrawals. For chains settling to Ethereum or an Arb
```suggestion
- **Shorter periods**: Suitable for applications that benefit from faster state confirmation, such as rollups prioritizing quicker exits or user withdrawals. For chains settling to Ethereum or an Arbitrum chain, this reduces challenge duration based on L1 block times.
```

2025-01-31 21:22 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Longer periods**: Recommended for applications requiring higher security, such as cross-chain asset transfers or large-value transactions. The actual time duration depends on the parent chain’s b
```suggestion
- **Longer periods**: Recommended for applications requiring higher security, such as cross-chain asset transfers or large-value transactions. The actual duration depends on the parent chain’s block intervals (e.g., Ethereum vs. other chains).
```

2025-01-31 21:25 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/how-tos/manage-fee-collectors.md
>  As part of the activity of an Orbit chain, different fees are collected with every transaction. These fees are collected as a single amount (the transaction fees) but are internally split into differ
```suggestion
Different fees get collected for every transaction as part of an Orbit chain activity. These fees are collected as a single amount (the transaction fees) but split internally into different components depending on their purpose. Each component is transferrable to a different fee collector address that is configurable on your chain.
```

2025-01-31 21:26 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/how-tos/manage-fee-collectors.md
> +This guide describes the different fees that are collected on your chain, how to configure them, and how to specify the fee collector address for each fee type.
```suggestion
This guide describes the different collected fees and explains how to specify the fee collector address on your chain for each fee type.
This guide describes the different fees collected on your chain, how to configure them, and how to specify the fee collector address for each type.
```

2025-01-31 21:26 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/how-tos/manage-fee-collectors.md
> +Let's see in what ways we can configure each fee type.
```suggestion
Let's see in what ways we can configure each fee type:
```

2025-01-31 21:27 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/how-tos/manage-fee-collectors.md
> +_Note: This minimum base fee defines the minimum value that the chain's base fee can have. However, in periods of congestion, the actual base fee might be higher than this minimum. Check the next sec
```suggestion
::: note
This minimum base fee defines the minimum value that the chain's base fee can have. However, in periods of congestion, the actual base fee might be higher than this minimum. Check the next section "Orbit surplus fee" for more information.
:::
```

2025-01-31 21:29 UTC, pete-vielhaber requested changes
Minor changes requested throughout for structure, grammar

2025-02-03 15:49 UTC, mahsamoosavi commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +Like the main challenge period, this parameter can be customized in two ways:
I'll change it to `Like the main challenge period, this parameter is customizable in two ways:`

2025-02-03 16:19 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +Like the main challenge period, this parameter can be customized in two ways:
works for me!

2025-02-04 16:20 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +In addition to the main challenge period, ** an extra challenge period ** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance secur
```suggestion
In addition to the main challenge period, **an extra challenge period** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance security and confirm the chain's state.
```
For some reason whitespaces where added here, removing the bold style.

2025-02-04 16:36 UTC, TucksonDev requested changes
Almost there!
I think the main issue left from my point of view (excluding nits) is the use of "parent chain's notion of block progression" which I believe is still confusing. Added one potential solution in the relevant comment, but happy to discuss further 🙏 
Thanks very much @mahsamoosavi !

2025-02-04 16:36 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +In addition to the main challenge period, ** an extra challenge period ** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance secur
```suggestion
In addition to the main challenge period, **an extra challenge period** provides a buffer to resolve any pending challenges after the main period ends. Together, these parameters help balance security and confirm the chain's state.
```
For some reason whitespaces where added here, removing the bold style.

2025-02-04 16:36 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethe
I think "parent chain's notion of block progression" might still be confusing. For an L3 chain, I'd think that Arbitrum's notion of block progression is measured in L2 blocks, not L1 blocks.

It's definitely tricky. Another solution I'm thinking about is that we lead the page with a section or admonition titled "How time is measured in challenges" and describe that chains settling to Ethereum or Arbitrum chains use `block.number` for all block calculations, which corespond to the chain's view of L1 block number.

Let me know what you think. We can also ask Gael and Pete in case they have a better idea.

2025-02-04 16:36 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethe
```suggestion
By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethereum or an Arbitrum chain. The default duration design is to provide sufficient time for validators to detect and challenge fraudulent assertions.
```
Or something like that. Same issue in the paragraph below.

2025-02-04 16:36 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +#### Challenge period blocks
```suggestion
### Challenge period blocks
```

2025-02-04 16:36 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +#### Extra challenge period blocks
```suggestion
### Extra challenge period blocks
```

2025-02-04 18:39 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +On the other hand, the extra challenge period adds a buffer of 200 blocks based on the parent chain’s notion of block progression. For chains settling to Ethereum, this corresponds to approximately 4
```suggestion
On the other hand, the extra challenge period adds a buffer of 200 blocks based on the parent chain’s notion of block progression. For chains settling to Ethereum or an Arbitrum chain, this corresponds to approximately 40 minutes. This time ensures that any last-minute challenges or ongoing dispute resolution processes can be completed before the rollup finalizes its state.
```

2025-02-04 18:42 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethe
I think the admonition makes sense, especially in the Orbit sections. I think trying to explain that within the text above may be confusing, so an admonition at the top (or even below this paragraph) would make more sense.

2025-02-04 18:43 UTC, pete-vielhaber approved these changes

2025-02-05 17:54 UTC, pete-vielhaber commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethe
Added admonition in the latest commit

2025-02-05 19:41 UTC, mahsamoosavi approved these changes
LGTM!

2025-02-06 12:40 UTC, TucksonDev requested changes
Let's see if these changes better clarify this `block.number` thingy! 😄

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +Chains settling to Ethereum or Arbitrum chains use `block.number` for all block calculations, which corespond to the chain's view of the parent chain block number.
```suggestion
Chains settling to Ethereum or Arbitrum chains use `block.number` for all block calculations, which corespond to the chain's view of Ethereum's block number. For example, an L3 Arbitrum chain settling to Arbitrum One, will calculate block progression based on Ethereum's (L1) block number.
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +By default, the challenge period lasts approximately one week, corresponding to the parent chain’s notion of block progression. This equates to roughly 45,818 L1 blocks for chains that settle to Ethe
```suggestion
By default, the challenge period lasts approximately one week, which equates to roughly 45,818 L1 blocks for chains that settle to Ethereum or an Arbitrum chain. The default duration design is to provide sufficient time for validators to detect and challenge fraudulent assertions.
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +On the other hand, the extra challenge period adds a buffer of 200 blocks based on the parent chain’s notion of block progression. For chains settling to Ethereum or an Arbitrum chain, this correspon
```suggestion
On the other hand, the extra challenge period adds a buffer of 40 minutes by default, 200 L1 blocks for chains settling to Ethereum or an Arbitrum chain. This time ensures that any last-minute challenges or ongoing dispute resolution processes can be completed before the rollup finalizes its state.
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +The main challenge period configuration uses the `confirmPeriodBlocks` parameter, which specifies the duration of the challenge window based on the parent chain’s notion of block progression. This pa
```suggestion
The main challenge period configuration uses the `confirmPeriodBlocks` parameter, which specifies the duration of the challenge window based on the parent chain’s notion of `block.number`. This parameter can is customizable in two ways:
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +2. **Post-deployment**: The chain owner can dynamically adjust the parameter using the `Rollup.setExtraChallengeTimeBlocks(newExtraTimeBlocks)` function. For example:
```suggestion
2. **Post-deployment**: The chain owner can dynamically adjust the parameter using the `Rollup.setExtraChallengeTimeBlocks(newExtraTimeBlocks)` function.
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +For example, the following command can update the extra challenge period to 300 blocks based on the parent chain’s notion of block progression:
```suggestion
For example, the following command can update the extra challenge period to 300 blocks based on the parent chain’s notion of `block.number`:
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Challenge period blocks**: 45,818 parent chain blocks (approximately one week).
```suggestion
- **Challenge period blocks**: 45,818 Ethereum blocks (approximately one week).
```

2025-02-06 12:40 UTC, TucksonDev commented on arbitrum-docs/launch-orbit-chain/02-configure-your-chain/common-configurations/02-customizable-challenge-period.mdx
> +- **Extra challenge period blocks**: 200 parent chain blocks (approximately 40 minutes).
```suggestion
- **Extra challenge period blocks**: 200 Ethereum blocks (approximately 40 minutes).
```

2025-02-08 01:23 UTC, merged