Add support for variables
OffchainLabs/arbitrum-docs pull request #260
Opened 2023-05-04 12:53 UTC by TucksonDev

Attempt to add support for variables within the docs. This PR presents the basic structure and a use case: node images

Current behaviour is:
- Any text, code or URL (in link tags) enclosed in @ characters can be replaced by the correspondant variable (e.g. @latestNitroVersion@)
- Variables are kept in `website/static/globalVars.js`

There are some limitations for this support:
- We can use other pattern, but if we want to support injecting variables in backticks enclosed texts, we can't use the following characters: [, {, (, |, &, = (probably some more). These characters are handled differently by docusaurus when converting those texts to "code" tags, to support syntax highlighting.
- Variables inside single backticks are not detected, but those can be replaced by <code> HTML tags (the behaviour is the same)

2023-05-04 13:23 UTC, mahsamoosavi approved these changes
This will make our lives much easier! 🧚🏻‍♀️

2023-05-04 13:25 UTC, DZGoldman commented on website/src/remark/variable-injector.js
> +      let value;
could use iffy syntax here (no necessary tho)

2023-05-04 13:26 UTC, DZGoldman commented on website/src/remark/variable-injector.js
> +      value = value.replace(/\@\s*([a-zA-Z0-9_-]+)\s*\@/g, (match, varName) => {
comment explaining in words? (I think just "stuff between two "@"s)?

2023-05-04 13:26 UTC, DZGoldman requested changes
pumped

2023-05-04 15:01 UTC, TucksonDev commented
@DZGoldman , I forgot to revisit that file after finishing with the rest of changes. I've added more clarification and removed outdated comments :)

2023-05-05 13:26 UTC, symbolpunk approved these changes

2023-05-05 18:57 UTC, DZGoldman approved these changes
lgtm

2023-05-08 09:06 UTC, merged