Improve testnets FAQs
OffchainLabs/arbitrum-docs pull request #280
Opened 2023-05-17 10:13 UTC by TucksonDev

When using the bridge connected to Goerli, a question pops up "What is Nitro testnet" that sends the user to an outdated FAQ in the support portal.
This PR adds an FAQ to Arbitrum's docs that answers that question better than the one present today.

- FAQ in support portal => https://consensys.zendesk.com/hc/en-us/articles/7277996058395
- Current FAQ => https://developer.arbitrum.io/for-devs/troubleshooting-building#is-there-any-testnet-or-devnet-available-on-arbitrum
- New FAQ => https://nitro-docs-git-improve-testnets-faqs-offchain-labs.vercel.app/for-devs/troubleshooting-building#what-is-a-testnet-or-a-devnet

2023-05-17 19:41 UTC, mahsamoosavi requested changes

2023-05-17 19:41 UTC, mahsamoosavi commented on arbitrum-docs/partials/_troubleshooting-building-partial.md
> +<p>Arbitrum testnets have the same full feature-set as the mainnet networks. They are also "true" L2s that run on top of public testnet Layer 1s, using their underlying networks for security and sett
Should we use the word testnet instead? Using it as plural may imply that we have more than one testnet available.
I'd just the following, please feel free to edit as you wish:

Nitro Goerli Rollup testnet has the same full feature-set as the mainnet networks. It is also a "true" L2 that runs on top of the Goerli testnet, using it for security and settlement

2023-05-17 19:41 UTC, mahsamoosavi commented on arbitrum-docs/partials/_troubleshooting-building-partial.md
> +<p>Users can bridge any asset from the underlying testnet L1 into an Arbitrum testnet (and back!), using the official <a href="https://bridge.arbitrum.io">bridge</a>.</p>
`Users can bridge any asset from the Goerli testnet (L1) into the Nitro Goerli Rollup testnet (and back!), using the official bridge`

2023-05-17 19:41 UTC, mahsamoosavi commented on arbitrum-docs/partials/_troubleshooting-building-partial.md
>  <p>Yes, there's a Goerli Rollup Testnet (421613) that uses the Nitro rollup tech stack, running on top of Ethereum Goerli. You can find more information <a href="https://developer.arbitrum.io/public-
should we change Testnet to testnet?

2023-05-18 10:33 UTC, TucksonDev commented
Thanks @mahsamoosavi ! Changes applied 💪

2023-05-18 13:45 UTC, mahsamoosavi approved these changes

2023-05-18 14:53 UTC, merged