Update bridge tutorial
OffchainLabs/arbitrum-docs pull request #513
Opened 2023-09-01 15:21 UTC by TucksonDev

This PR updates the Bridge tutorial:
- Adds the notion of bridging from a parent chain to a child chain (with examples for new users)
- Adapts the contents to follow standard pattern guides
- Prioritizes Arbitrum Sepolia over Arbitrum Goerli

Preview

2023-09-01 15:31 UTC, mahsamoosavi requested changes

2023-09-01 15:31 UTC, mahsamoosavi commented on arbitrum-docs/getting-started-users.mdx
> +- If you are using a testnet, requesting funds from a faucet for [Sepolia](https://sepoliafaucet.com/), [Goerli](https://goerlifaucet.com) or [Arbitrum Sepolia](https://faucet.quicknode.com/arbitrum/
```suggestion
- If you are using a testnet, requesting funds from a faucet for [Sepolia](https://sepoliafaucet.com/), [Goerli](https://goerlifaucet.com) or [Arbitrum Sepolia](https://faucet.quicknode.com/arbitrum/sepolia).
```

2023-09-01 15:31 UTC, mahsamoosavi commented on arbitrum-docs/getting-started-users.mdx
> +### Step 2: Add the network to your wallet
should we say "Add the preferred network to your wallet"?

2023-09-01 15:31 UTC, mahsamoosavi commented on arbitrum-docs/getting-started-users.mdx
> +To bridge your ETH or ERC-20 tokens to a different chain, start by visiting [bridge.arbitrum.io](https://bridge.arbitrum.io/). Login to the bridge with your wallet and make sure you are connected to
```suggestion
To bridge your ETH or ERC-20 tokens to a different chain, start by visiting [bridge.arbitrum.io](https://bridge.arbitrum.io/). Log in to the bridge with your wallet and make sure you are connected to the source network (from where you want to deposit your assets) at the top of the page. Then, select the destination network (where you want your assets to go), e.g., Arbitrum One or Arbitrum Nova.
```

2023-09-01 15:31 UTC, mahsamoosavi commented on arbitrum-docs/getting-started-users.mdx
> +Once the countdown is done, switch to the destination network on your wallet and press the `Claim` button that has now turned blue to receive your funds!
```suggestion
Once the countdown is done, switch to the destination network on your wallet and press the `Claim` button, that has now turned blue, to receive your funds!
```

2023-09-01 15:31 UTC, mahsamoosavi commented on arbitrum-docs/getting-started-users.mdx
> +## What's Next?
```suggestion
## What's next?
```

2023-09-01 15:36 UTC, mahsamoosavi approved these changes

2023-09-07 15:37 UTC, symbolpunk approved these changes
BAMF

2023-09-07 15:37 UTC, merged