chain params page and global vars
OffchainLabs/arbitrum-docs pull request #517
Opened 2023-09-01 19:18 UTC by DZGoldman

2023-09-04 13:23 UTC, TucksonDev commented
For some reason, Vercel didn't update the URL of the latest deployed version, but kept the initial one. Here's the latest URL: https://nitro-docs-git-chain-params-offchain-labs.vercel.app/

2023-09-04 13:27 UTC, TucksonDev commented on arbitrum-docs/for-devs/chain-params.mdx
> +---
Should we use Sentence-case for the title, sidebar and parameter names here?

2023-09-04 13:31 UTC, TucksonDev requested changes
That new page is going to help a lot, thanks @DZGoldman !
Requesting changes only about its title, sidebar and names being in sentence-case.

2023-09-05 16:10 UTC, TucksonDev approved these changes

2023-09-07 15:42 UTC, symbolpunk approved these changes

2023-09-07 15:42 UTC, merged