Add NodeInterface pages
OffchainLabs/arbitrum-docs pull request #724
Opened 2023-10-25 20:39 UTC by TucksonDev

This PR improves the information available about the NodeInterface. It creates a concept page and a reference page, autogenerating the table that contains the methods available in the NodeInterface. It also changes all previous links going to the short section in the L2 gas page to the new concept or reference page.

Concept page
Reference page

2023-10-26 14:22 UTC, mahsamoosavi requested changes
a few suggestions, otherwise looks 🔥

2023-10-26 14:22 UTC, mahsamoosavi commented on arbitrum-docs/arbos/gas.mdx
> +Gas estimation for Retryable submissions is possible via the [NodeInterface](/for-devs/dev-tools-and-resources/nodeinterface.mdx) and similarly requires the auto-redeem attempt succeed.
```suggestion
Gas estimation for Retryable submissions is possible via the [NodeInterface](/for-devs/dev-tools-and-resources/nodeinterface.mdx) and similarly requires the auto-redeem attempt to succeed.
```

2023-10-26 14:22 UTC, mahsamoosavi commented on arbitrum-docs/arbos/l1-pricing.mdx
>  ## Getting L1 Fee Info
```suggestion
## Getting L1 fee info
```

2023-10-26 14:22 UTC, mahsamoosavi commented on arbitrum-docs/for-devs/concepts/nodeinterface.mdx
> +The Arbitrum Nitro software includes a special `NodeInterface` contract available at address `0xc8` that is only accessible via RPCs (it's not actually deployed on-chain, and thus can't be called by
```suggestion
The Arbitrum Nitro software includes a special `NodeInterface` contract available at address `0xc8` that is only accessible via RPCs (it's not actually deployed on-chain, and thus can't be called by smart contracts). The way it works is that the node uses Geth's [`InterceptRPCMessage`](https://github.com/OffchainLabs/go-ethereum/blob/@goEthereumCommit@/internal/ethapi/api.go#L1034) hook to detect messages sent to the address `0xc8`, and swaps out the message it's handling before deriving a transaction from it.
```

2023-10-26 15:00 UTC, TucksonDev commented
Thanks @mahsamoosavi ! 🙏 
Btw, those pages under the `arbos` folder still need a deep rework (my intention was just to change the links pointing to the new NodeInterface page).

2023-10-26 15:10 UTC, symbolpunk approved these changes
Very cool 😎

2023-10-27 16:48 UTC, mahsamoosavi approved these changes

2023-10-27 16:53 UTC, merged