Add new assets and quickstart guide to Japanese documentation
OffchainLabs/arbitrum-docs pull request #788
Opened 2023-12-04 04:29 UTC by funkyenough

- Add new images (cargo-stylus.png and stylus-wallet.png) to assets
- Add translated stylus-quickstart.md file

2023-12-04 23:57 UTC, funkyenough commented on website/i18n/ja/docusaurus-plugin-content-docs/translated/stylus/stylus-quickstart.md
> +import PublicPreviewBannerPartial from './partials/_stylus-public-preview-banner.md';
Understood. 

- Added banner to `./partials/_stylus-public-preview-banner-partial.md`
- Changed import message to `import PublicPreviewBannerPartial from './partials/_stylus-public-preview-banner-partial.md';`

2023-12-06 05:15 UTC, hkalodner commented
@cla-bot check

2023-12-06 05:16 UTC, hkalodner commented
@cla-bot check

2023-12-11 16:15 UTC, symbolpunk approved these changes
Love the way this was integrated - thank you!

LGTM from a structural perspective, cc @Jason-W123 to merge whenever you're ready :)

2023-12-12 07:18 UTC, Jason-W123 commented on website/i18n/ja/docusaurus-plugin-content-docs/translated/stylus/reference/rust-sdk-guide.md
> +import PublicPreviewBannerPartial from '../partials/_stylus-public-preview-banner.md';
There is no file named `_stylus-public-preview-banner.md`, you mean `_stylus-public-preview-banner.md_partial.md`?

2023-12-12 07:18 UTC, Jason-W123 commented on website/i18n/ja/docusaurus-plugin-content-docs/translated/stylus/reference/stylus-sdk.md
> +import PublicPreviewBannerPartial from '../partials/_stylus-public-preview-banner.md';
Same as above

2023-12-12 07:18 UTC, Jason-W123 commented on website/i18n/ja/docusaurus-plugin-content-docs/translated/stylus/reference/testnet-information.md
> +import PublicPreviewBannerPartial from '../partials/_stylus-public-preview-banner.md';
Same here

2023-12-12 13:23 UTC, Jason-W123 requested changes

2023-12-12 13:23 UTC, Jason-W123 commented on website/i18n/ja/docusaurus-plugin-content-docs/translated/stylus/reference/stylus-sdk.md
> +import TranslationBannerPartial from "./partials/_stylus-translation-banner-partial.md";
If you want to import from `reference` dir, you should change the path to `../partials/xxx`. (Not only this file, but all files under `reference`)
```suggestion
import TranslationBannerPartial from "../partials/_stylus-translation-banner-partial.md";
```

2023-12-13 06:35 UTC, merged