Add orbit information to node running page
OffchainLabs/arbitrum-docs pull request #789
Opened 2023-12-05 08:30 UTC by Jason-W123

2023-12-05 14:51 UTC, mahsamoosavi requested changes

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - It must provide a standard evm node RPC endpoint that you run yourself or from a node provider
```suggestion
  - It must provide a standard RPC endpoint for an EVM node, whether self-hosted or obtained from a node service provider
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - Would be set to appropriate Arb1, Nova, Sepolia RPC URL
```suggestion
  - Would be set to appropriate Arbitrum One, Arbitrum Nova, or Arbitrum Sepolia RPC URL
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - Note: [Arbitrum.io public RPCs](/node-running/node-providers.mdx) will rate limit connections, will need to run local node for parent chain or use 3rd party RPC providers
```suggestion
  - Note: [Arbitrum.io public RPCs](/node-running/node-providers.mdx) will rate limit connections, you will need to run a local node for the parent chain or relay on third party RPC providers
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - `nodeConfig.json` will be generated when orbit chain is created, you need to set it using either `--conf.file` or `--chain.info-json`
```suggestion
  - `nodeConfig.json` will be generated when an Orbit chain is created, you need to set it using either `--conf.file` or `--chain.info-json` 
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - `--conf.file` is the docker container's path of `nodeConfig.json`, you need put this file to mount point first. `--chain.info-json` is the json content itself
```suggestion
  - `--conf.file` refers to the Docker container's location of `nodeConfig.json`. Initially, you must place this file at the designated mount point. As for -`-chain.info-json`, it represents the actual JSON content
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - `--chain.name="My Arbitrum L3 Chain"` must be provided, and matches the chain name used in `--conf.file` file or `--chain.info-json` content
```suggestion
  - `--chain.name="My Arbitrum L3 Chain"` must be provided, and it must match the chain name that is used in `--conf.file` file or `--chain.info-json` content
```

2023-12-05 14:51 UTC, mahsamoosavi commented on arbitrum-docs/node-running/how-tos/running-a-full-node.mdx
> +  - If anytrust chain, also need to supply `--node.data-availablity.enable` and then some ways to get the data like `--node.data-availability.rest-aggregator.enable` and associated options or `--node
```suggestion
  - For an Anytrust chain, it is essential to provide `--node.data-availability.enable`. Additionally, you must choose a method for obtaining the data, such as enabling `--node.data-availability.rest-aggregator.enable` with its associated options, or opting for `--node.data-availability.ipfs-storage.enable` along with its associated options
```

2023-12-08 07:56 UTC, closed without merging

2023-12-08 07:56 UTC, Jason-W123 commented
Close it as we have new plan