Add new FAQs
OffchainLabs/arbitrum-docs pull request #810
Opened 2023-12-14 14:03 UTC by TucksonDev

2023-12-15 02:34 UTC, mahsamoosavi requested changes

2023-12-15 02:34 UTC, mahsamoosavi commented on website/static/get-started-faqs.json
> +{"question": "Can I withdraw my funds from Arbitrum back to Ethereum without going through the sequencer? What about funds that are in a contract?","answer": "<p>Yes, it is possible to permissionlesl
```suggestion
{"question": "Can I withdraw my funds from Arbitrum back to Ethereum without going through the Sequencer? What about funds that are in a contract?","answer": "<p>Yes, it is possible to permissionlessly send a message from Ethereum to be executed on Arbitrum, and bypassing the Sequencer. You can do this by using the DelayedInbox contract and force-including the message after a certain amount of time has passed (currently ~24 hours). You can find more information about this behavior <a href=\"https://docs.arbitrum.io/sequencer#unhappyuncommon-case-sequencer-isnt-doing-its-job\">here</a>.</p>\n\n<p>Keep in mind that you can execute any message in this way, be it a withdrawal of funds back to Ethereum, or a call to a contract.</p>\n\n<p>You can also find an example of force-inclusion in <a href=\"https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/delayedInbox-l2msg\">this tutorial</a>. </p>\n\n<p></p>\n\n","key": "can-i-withdraw-my-funds-from-arbitrum-back-to-ethereum-without-going-through-the-sequencer-what-about-funds-that-are-in-a-contract"},
```

2023-12-15 02:34 UTC, mahsamoosavi commented on website/static/node-running-faqs.json
> +{"question": "When querying classic transactions from a Nitro node, I sometimes get incorrect data, like the zero address as the sender. Why is that?","answer": "<p>Some old Nitro genesis database sn
```suggestion
{"question": "When querying Classic transactions from a Nitro node, I sometimes get incorrect data, like the zero address as the sender. Why is that?","answer": "<p>Some old Nitro genesis database snapshots didn't properly set the retry sender for Classic blocks and contain said error. If you need to access that information, you can either resync your nitro node with one of the <a href=\"https://snapshot.arbitrum.foundation/index.html\">current snapshots</a>, or <a href=\"https://docs.arbitrum.io/node-running/how-tos/running-a-classic-node\">run a Classic node</a> along with your nitro node and configure a redirection for requests to classic blocks. Please note that this only happens on Arbitrum One.</p>\n\n<p></p>\n\n","key": "when-querying-classic-transactions-from-a-nitro-node-i-sometimes-get-incorrect-data-like-the-zero-address-as-the-sender-why-is-that"}
```

2023-12-18 15:34 UTC, symbolpunk approved these changes
LGTM! One non-blocking nit (applied to Notion already)

2023-12-18 15:34 UTC, symbolpunk commented on website/static/get-started-faqs.json
> +{"question": "Can I withdraw my funds from Arbitrum back to Ethereum without going through the sequencer? What about funds that are in a contract?","answer": "<p>Yes, it is possible to permissionless
```suggestion
{"question": "Can I withdraw my funds from Arbitrum back to Ethereum without going through the sequencer? What about funds that are in a contract?","answer": "<p>Yes, it is possible to permissionlessly send a message from Ethereum to be executed on Arbitrum, while bypassing the Sequencer. You can do this by using the DelayedInbox contract and force-including the message after a certain amount of time has passed (currently ~24 hours). You can find more information about this behavior <a href=\"https://docs.arbitrum.io/sequencer#unhappyuncommon-case-sequencer-isnt-doing-its-job\">here</a>.</p>\n\n<p>Keep in mind that you can execute any message in this way, be it a withdrawal of funds back to Ethereum, or a call to a contract.</p>\n\n<p>You can also find an example of force-inclusion in <a href=\"https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/delayedInbox-l2msg\">this tutorial</a>. </p>\n\n<p></p>\n\n","key": "can-i-withdraw-my-funds-from-arbitrum-back-to-ethereum-without-going-through-the-sequencer-what-about-funds-that-are-in-a-contract"},
```

non-blocking nit (FAQ CMS entry has been updated)

2023-12-18 15:38 UTC, mahsamoosavi approved these changes
LGTM :)

2023-12-18 15:47 UTC, merged